// flow-typed signature: 2649a1d596e8b2b208b5c46ce9ccee76
// flow-typed version: <<STUB>>/farce_v0.4.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'farce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'farce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'farce/cjs/Actions' {
  declare module.exports: any;
}

declare module 'farce/cjs/ActionTypes' {
  declare module.exports: any;
}

declare module 'farce/cjs/BrowserProtocol' {
  declare module.exports: any;
}

declare module 'farce/BrowserProtocol' {
  declare module.exports: any;
}

declare module 'farce/cjs/createBasenameMiddleware' {
  declare module.exports: any;
}

declare module 'farce/cjs/createHistoryEnhancer' {
  declare module.exports: any;
}

declare module 'farce/cjs/createHistoryMiddleware' {
  declare module.exports: any;
}

declare module 'farce/cjs/createLocationMiddleware' {
  declare module.exports: any;
}

declare module 'farce/cjs/createNavigationListenerMiddleware' {
  declare module.exports: any;
}

declare module 'farce/cjs/createPath' {
  declare module.exports: any;
}

declare module 'farce/cjs/createQueryMiddleware' {
  declare module.exports: any;
}

declare module 'farce/cjs/ensureLocation' {
  declare module.exports: any;
}

declare module 'farce/cjs/ensureLocationMiddleware' {
  declare module.exports: any;
}

declare module 'farce/cjs/HashProtocol' {
  declare module.exports: any;
}

declare module 'farce/cjs' {
  declare module.exports: any;
}

declare module 'farce/cjs/locationReducer' {
  declare module.exports: any;
}

declare module 'farce/cjs/MemoryProtocol' {
  declare module.exports: any;
}

declare module 'farce/cjs/queryMiddleware' {
  declare module.exports: any;
}

declare module 'farce/queryMiddleware' {
  declare module.exports: any;
}

declare module 'farce/cjs/ServerProtocol' {
  declare module.exports: any;
}

declare module 'farce/cjs/StateStorage' {
  declare module.exports: any;
}

declare module 'farce/esm/Actions' {
  declare module.exports: any;
}

declare module 'farce/esm/ActionTypes' {
  declare module.exports: any;
}

declare module 'farce/esm/BrowserProtocol' {
  declare module.exports: any;
}

declare module 'farce/esm/createBasenameMiddleware' {
  declare module.exports: any;
}

declare module 'farce/esm/createHistoryEnhancer' {
  declare module.exports: any;
}

declare module 'farce/esm/createHistoryMiddleware' {
  declare module.exports: any;
}

declare module 'farce/esm/createLocationMiddleware' {
  declare module.exports: any;
}

declare module 'farce/esm/createNavigationListenerMiddleware' {
  declare module.exports: any;
}

declare module 'farce/esm/createPath' {
  declare module.exports: any;
}

declare module 'farce/esm/createQueryMiddleware' {
  declare module.exports: any;
}

declare module 'farce/esm/ensureLocation' {
  declare module.exports: any;
}

declare module 'farce/esm/ensureLocationMiddleware' {
  declare module.exports: any;
}

declare module 'farce/esm/HashProtocol' {
  declare module.exports: any;
}

declare module 'farce/esm' {
  declare module.exports: any;
}

declare module 'farce/esm/locationReducer' {
  declare module.exports: any;
}

declare module 'farce/esm/MemoryProtocol' {
  declare module.exports: any;
}

declare module 'farce/esm/queryMiddleware' {
  declare module.exports: any;
}

declare module 'farce/esm/ServerProtocol' {
  declare module.exports: any;
}

declare module 'farce/esm/StateStorage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'farce/cjs/Actions.js' {
  declare module.exports: $Exports<'farce/cjs/Actions'>;
}
declare module 'farce/cjs/ActionTypes.js' {
  declare module.exports: $Exports<'farce/cjs/ActionTypes'>;
}
declare module 'farce/cjs/BrowserProtocol.js' {
  declare module.exports: $Exports<'farce/cjs/BrowserProtocol'>;
}
declare module 'farce/cjs/createBasenameMiddleware.js' {
  declare module.exports: $Exports<'farce/cjs/createBasenameMiddleware'>;
}
declare module 'farce/cjs/createHistoryEnhancer.js' {
  declare module.exports: $Exports<'farce/cjs/createHistoryEnhancer'>;
}
declare module 'farce/cjs/createHistoryMiddleware.js' {
  declare module.exports: $Exports<'farce/cjs/createHistoryMiddleware'>;
}
declare module 'farce/cjs/createLocationMiddleware.js' {
  declare module.exports: $Exports<'farce/cjs/createLocationMiddleware'>;
}
declare module 'farce/cjs/createNavigationListenerMiddleware.js' {
  declare module.exports: $Exports<'farce/cjs/createNavigationListenerMiddleware'>;
}
declare module 'farce/cjs/createPath.js' {
  declare module.exports: $Exports<'farce/cjs/createPath'>;
}
declare module 'farce/cjs/createQueryMiddleware.js' {
  declare module.exports: $Exports<'farce/cjs/createQueryMiddleware'>;
}
declare module 'farce/cjs/ensureLocation.js' {
  declare module.exports: $Exports<'farce/cjs/ensureLocation'>;
}
declare module 'farce/cjs/ensureLocationMiddleware.js' {
  declare module.exports: $Exports<'farce/cjs/ensureLocationMiddleware'>;
}
declare module 'farce/cjs/HashProtocol.js' {
  declare module.exports: $Exports<'farce/cjs/HashProtocol'>;
}
declare module 'farce/cjs/index' {
  declare module.exports: $Exports<'farce/cjs'>;
}
declare module 'farce/cjs/index.js' {
  declare module.exports: $Exports<'farce/cjs'>;
}
declare module 'farce/cjs/locationReducer.js' {
  declare module.exports: $Exports<'farce/cjs/locationReducer'>;
}
declare module 'farce/cjs/MemoryProtocol.js' {
  declare module.exports: $Exports<'farce/cjs/MemoryProtocol'>;
}
declare module 'farce/cjs/queryMiddleware.js' {
  declare module.exports: $Exports<'farce/cjs/queryMiddleware'>;
}
declare module 'farce/cjs/ServerProtocol.js' {
  declare module.exports: $Exports<'farce/cjs/ServerProtocol'>;
}
declare module 'farce/cjs/StateStorage.js' {
  declare module.exports: $Exports<'farce/cjs/StateStorage'>;
}
declare module 'farce/esm/Actions.js' {
  declare module.exports: $Exports<'farce/esm/Actions'>;
}
declare module 'farce/esm/ActionTypes.js' {
  declare module.exports: $Exports<'farce/esm/ActionTypes'>;
}
declare module 'farce/esm/BrowserProtocol.js' {
  declare module.exports: $Exports<'farce/esm/BrowserProtocol'>;
}
declare module 'farce/esm/createBasenameMiddleware.js' {
  declare module.exports: $Exports<'farce/esm/createBasenameMiddleware'>;
}
declare module 'farce/esm/createHistoryEnhancer.js' {
  declare module.exports: $Exports<'farce/esm/createHistoryEnhancer'>;
}
declare module 'farce/esm/createHistoryMiddleware.js' {
  declare module.exports: $Exports<'farce/esm/createHistoryMiddleware'>;
}
declare module 'farce/esm/createLocationMiddleware.js' {
  declare module.exports: $Exports<'farce/esm/createLocationMiddleware'>;
}
declare module 'farce/esm/createNavigationListenerMiddleware.js' {
  declare module.exports: $Exports<'farce/esm/createNavigationListenerMiddleware'>;
}
declare module 'farce/esm/createPath.js' {
  declare module.exports: $Exports<'farce/esm/createPath'>;
}
declare module 'farce/esm/createQueryMiddleware.js' {
  declare module.exports: $Exports<'farce/esm/createQueryMiddleware'>;
}
declare module 'farce/esm/ensureLocation.js' {
  declare module.exports: $Exports<'farce/esm/ensureLocation'>;
}
declare module 'farce/esm/ensureLocationMiddleware.js' {
  declare module.exports: $Exports<'farce/esm/ensureLocationMiddleware'>;
}
declare module 'farce/esm/HashProtocol.js' {
  declare module.exports: $Exports<'farce/esm/HashProtocol'>;
}
declare module 'farce/esm/index' {
  declare module.exports: $Exports<'farce/esm'>;
}
declare module 'farce/esm/index.js' {
  declare module.exports: $Exports<'farce/esm'>;
}
declare module 'farce/esm/locationReducer.js' {
  declare module.exports: $Exports<'farce/esm/locationReducer'>;
}
declare module 'farce/esm/MemoryProtocol.js' {
  declare module.exports: $Exports<'farce/esm/MemoryProtocol'>;
}
declare module 'farce/esm/queryMiddleware.js' {
  declare module.exports: $Exports<'farce/esm/queryMiddleware'>;
}
declare module 'farce/esm/ServerProtocol.js' {
  declare module.exports: $Exports<'farce/esm/ServerProtocol'>;
}
declare module 'farce/esm/StateStorage.js' {
  declare module.exports: $Exports<'farce/esm/StateStorage'>;
}
