// flow-typed signature: d3883d518187f316c85dff73c6f5484e
// flow-typed version: <<STUB>>/found-relay_v0.8.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'found-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'found-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'found-relay/es' {
  declare module.exports: any;
}

declare module 'found-relay/es/QuerySubscription' {
  declare module.exports: any;
}

declare module 'found-relay/es/ReadyStateRenderer' {
  declare module.exports: any;
}

declare module 'found-relay/es/renderElement' {
  declare module.exports: any;
}

declare module 'found-relay/es/Resolver' {
  declare module.exports: any;
}

declare module 'found-relay/lib' {
  declare module.exports: any;
}

declare module 'found-relay/lib/QuerySubscription' {
  declare module.exports: any;
}

declare module 'found-relay/lib/ReadyStateRenderer' {
  declare module.exports: any;
}

declare module 'found-relay/lib/renderElement' {
  declare module.exports: any;
}

declare module 'found-relay/lib/Resolver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'found-relay/es/index' {
  declare module.exports: $Exports<'found-relay/es'>;
}
declare module 'found-relay/es/index.js' {
  declare module.exports: $Exports<'found-relay/es'>;
}
declare module 'found-relay/es/QuerySubscription.js' {
  declare module.exports: $Exports<'found-relay/es/QuerySubscription'>;
}
declare module 'found-relay/es/ReadyStateRenderer.js' {
  declare module.exports: $Exports<'found-relay/es/ReadyStateRenderer'>;
}
declare module 'found-relay/es/renderElement.js' {
  declare module.exports: $Exports<'found-relay/es/renderElement'>;
}
declare module 'found-relay/es/Resolver.js' {
  declare module.exports: $Exports<'found-relay/es/Resolver'>;
}
declare module 'found-relay/lib/index' {
  declare module.exports: $Exports<'found-relay/lib'>;
}
declare module 'found-relay/lib/index.js' {
  declare module.exports: $Exports<'found-relay/lib'>;
}
declare module 'found-relay/lib/QuerySubscription.js' {
  declare module.exports: $Exports<'found-relay/lib/QuerySubscription'>;
}
declare module 'found-relay/lib/ReadyStateRenderer.js' {
  declare module.exports: $Exports<'found-relay/lib/ReadyStateRenderer'>;
}
declare module 'found-relay/lib/renderElement.js' {
  declare module.exports: $Exports<'found-relay/lib/renderElement'>;
}
declare module 'found-relay/lib/Resolver.js' {
  declare module.exports: $Exports<'found-relay/lib/Resolver'>;
}
