// flow-typed signature: 13e798883d2f34100cc0cea6be693a97
// flow-typed version: <<STUB>>/passport-azure-ad_v4.0.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-azure-ad'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-azure-ad' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-azure-ad/Gruntfile' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/aadutils' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/bearerstrategy' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/constants' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/cookieContentHandler' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/errors/badrequesterror' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/errors/internaloautherror' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/errors/internalopeniderror' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/jsonWebToken' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/jwe' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/logging' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/metadata' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/oidcstrategy' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/pem' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/sessionContentHandler' {
  declare module.exports: any;
}

declare module 'passport-azure-ad/lib/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-azure-ad/Gruntfile.js' {
  declare module.exports: $Exports<'passport-azure-ad/Gruntfile'>;
}
declare module 'passport-azure-ad/lib/aadutils.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/aadutils'>;
}
declare module 'passport-azure-ad/lib/bearerstrategy.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/bearerstrategy'>;
}
declare module 'passport-azure-ad/lib/constants.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/constants'>;
}
declare module 'passport-azure-ad/lib/cookieContentHandler.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/cookieContentHandler'>;
}
declare module 'passport-azure-ad/lib/errors/badrequesterror.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/errors/badrequesterror'>;
}
declare module 'passport-azure-ad/lib/errors/internaloautherror.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/errors/internaloautherror'>;
}
declare module 'passport-azure-ad/lib/errors/internalopeniderror.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/errors/internalopeniderror'>;
}
declare module 'passport-azure-ad/lib/index' {
  declare module.exports: $Exports<'passport-azure-ad/lib'>;
}
declare module 'passport-azure-ad/lib/index.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib'>;
}
declare module 'passport-azure-ad/lib/jsonWebToken.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/jsonWebToken'>;
}
declare module 'passport-azure-ad/lib/jwe.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/jwe'>;
}
declare module 'passport-azure-ad/lib/logging.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/logging'>;
}
declare module 'passport-azure-ad/lib/metadata.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/metadata'>;
}
declare module 'passport-azure-ad/lib/oidcstrategy.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/oidcstrategy'>;
}
declare module 'passport-azure-ad/lib/pem.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/pem'>;
}
declare module 'passport-azure-ad/lib/sessionContentHandler.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/sessionContentHandler'>;
}
declare module 'passport-azure-ad/lib/validator.js' {
  declare module.exports: $Exports<'passport-azure-ad/lib/validator'>;
}
