// flow-typed signature: b09d8721a7665191c90af0c567b8b3cf
// flow-typed version: <<STUB>>/uuid-buffer_v1.0.3/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uuid-buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uuid-buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uuid-buffer/dist/uuid-buffer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uuid-buffer/dist/uuid-buffer.js' {
  declare module.exports: $Exports<'uuid-buffer/dist/uuid-buffer'>;
}
